name: Build Sofle Vial Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile BIN
        run: |
          make sofle/rev1:vial CONVERT_TO=promicro_stm32f103

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sofle_vial_firmware
          path: |
            *.bin
            *.hex
            *.uf2
